# Generated by Django 5.2 on 2025-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fashion_category',
            field=models.CharField(blank=True, choices=[('Women’s Clothing', 'Women’s Clothing'), ('Men’s Clothing', 'Men’s Clothing'), ('Kids & Baby', 'Kids & Baby'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Sportswear', 'Sportswear')], max_length=50, null=True),
        ),
    ]
