# Generated by Django 5.2 on 2025-05-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_fashion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fashion_category',
        ),
    ]
