# Generated by Django 5.2 on 2025-05-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_fashion_category'),
        ('vendors', '0006_remove_vendor_categories_vendor_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='vendors.vendorcategory'),
        ),
    ]
