# Generated by Django 5.2 on 2025-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
