# Generated by Django 5.2 on 2025-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='categories',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('food', 'Food & Beverage')], default='electronics', max_length=20),
        ),
    ]
