# Generated by Django 5.2 on 2025-05-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorcategory_remove_vendor_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='categories',
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.vendorcategory'),
        ),
    ]
