# Generated by Django 5.2 on 2025-05-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_vendor_categories_vendor_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='categories',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='vendors.vendorcategory'),
            preserve_default=False,
        ),
    ]
